platform :ios, '10.0'

target 'DBApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBApp
pod 'ALBNoSQLDB', :path => '../ALBNoSQLDB'
end
